Repository influxdata/docs-v2, pull requests merged in 2022-09, with the labels that each got.

#4401 feat: add MIT license to api content
  api-docs/openapi/content/cloud/info.yml
  api-docs/openapi/content/cloud/v1compat/info.yml
  api-docs/openapi/content/v2.0/info.yml
  api-docs/openapi/content/v2.1/info.yml
  api-docs/openapi/content/v2.1/v1compat/info.yml
  api-docs/openapi/content/v2.2/info.yml
  api-docs/openapi/content/v2.2/v1compat/info.yml
  api-docs/openapi/content/v2.3/info.yml
  api-docs/openapi/content/v2.3/v1compat/info.yml
  api-docs/openapi/content/v2.4/info.yml
  api-docs/openapi/content/v2.4/v1compat/info.yml
Labels: feat

#4413 feat: add instructions to set directory permissions on manually installs
  content/influxdb/v2.4/install.md
Labels: feat

#4437 feat: release api docs updates or Organization endpoints
  api-docs/cloud/ref.yml
  api-docs/v2.4/ref.yml
Labels: feat

#4458 fix(api): expand URL replacement to descriptions in schema nodes
  api-docs/openapi/plugins/decorators/replace-shortcodes.js
Labels: api, fix

#4469 chore(api): Updates API specs for users and auths. Fixes whitespace, …
  api-docs/cloud/ref.yml
  api-docs/cloud/swaggerV1Compat.yml
  api-docs/v2.4/ref.yml
  api-docs/v2.4/swaggerV1Compat.yml
Labels: chore

#4479 feat: dar-331 - Add Scheduled Tasks SLA information
  content/influxdb/v2.4/process-data/get-started.md
  content/influxdb/v2.4/process-data/manage-tasks/task-run-history.md
Labels: feat
