Repository influxdata/docs-v2, pull requests merged in 2022-04, with the labels that each got.

#3936 Add documentation for replications max-age
  content/influxdb/v2.2/reference/cli/influx/replication/create.md
  content/influxdb/v2.2/reference/cli/influx/replication/update.md
Labels: OSS, v2.2

#3944 chore: durability updates for TSM snapshots
  content/influxdb/cloud/reference/internals/durability.md
Labels: chore

#3966 fix: add missing `remotes`/`replications` `auth create` flags
  content/influxdb/v2.2/reference/cli/influx/auth/create.md
Labels: fix

#3901 fix: update RPM/DEB repo URLS
  content/telegraf/v1.22/install.md
Labels: fix

#3985 feat: package was removed from flux
  content/flux/v0.x/stdlib/contrib/jsternberg/rows/_index.md
  content/flux/v0.x/stdlib/contrib/jsternberg/rows/map.md
Labels: feat
