Repository influxdata/docs-v2, pull requests merged in 2022-07, with the labels that each got.

#4206 fix: add field to example annotated csv
  content/influxdb/v2.0/reference/syntax/annotated-csv/_index.md
  content/influxdb/v2.1/reference/syntax/annotated-csv/_index.md
  content/influxdb/v2.2/reference/syntax/annotated-csv/_index.md
  content/influxdb/v2.3/reference/syntax/annotated-csv/_index.md
Labels: fix

#4242 hotfix(tasks): update duplicate-oss tag to fix broken icon render.
  content/influxdb/cloud/process-data/manage-tasks/update-task.md
  content/influxdb/cloud/process-data/manage-tasks/view-tasks.md
  content/influxdb/v2.3/process-data/manage-tasks/update-task.md
Labels: ui, fix

#4223 feat: added CLI scripts documentation
  content/influxdb/v2.3/reference/cli/influx/_index.md
  content/influxdb/v2.3/reference/cli/influx/scripts/_index.md
  content/influxdb/v2.3/reference/cli/influx/scripts/create.md
  content/influxdb/v2.3/reference/cli/influx/scripts/delete.md
  content/influxdb/v2.3/reference/cli/influx/scripts/invoke.md
  content/influxdb/v2.3/reference/cli/influx/scripts/list.md
  content/influxdb/v2.3/reference/cli/influx/scripts/retrieve.md
  content/influxdb/v2.3/reference/cli/influx/scripts/update.md
Labels: feat

#4198 feat: add ast to glossary
  content/influxdb/v2.2/reference/glossary.md
  content/influxdb/v2.3/reference/glossary.md
Labels: feat

#4274 fix: json example, string example
  content/influxdb/v2.3/write-data/no-code/load-data.md
Labels: fix

#4265 chore(api): update Cloud and v2.3 API specs with latest openapi updates.
  api-docs/cloud/ref.yml
  api-docs/v2.3/ref.yml
Labels: chore

#4227 fix: remove extra bracket preventing URL formatting
  content/resources/videos/API-Invokable-Scripts.md
Labels: fix
