Repository influxdata/docs-v2, pull requests merged in 2022-10, with the labels that each got.

#4528 fix: add imports to query script
  content/influxdb/v2.4/api-guide/client-libraries/python.md
Labels: fix

#4545 hotfix: add missing link.
  content/influxdb/v2.4/install.md
Labels: bug

#4546 chore: Update API ref docs from openapi Cloud and OSS
  api-docs/cloud/ref.yml
  api-docs/v2.4/ref.yml
Labels: chore

#4548 fix: clarify OSS to OSS, Cloud, Enterprise
  content/influxdb/cloud/write-data/replication/_index.md
  content/influxdb/cloud/write-data/replication/replicate-data.md
  content/influxdb/v2.2/write-data/replication/_index.md
  content/influxdb/v2.4/write-data/replication/_index.md
  content/influxdb/v2.4/write-data/replication/replicate-data.md
Labels: fix

#4592 fix(tokens): Link to /me/tokens for Cloud (Closes #4591)
  content/influxdb/v2.4/security/tokens/create-token.md
Labels: fix
