Repository influxdata/docs-v2, pull requests merged in 2022-03, with the labels that each got.

#3827 Flux 0.157
  content/flux/v0.x/release-notes.md
Labels: Flux

#3832 fix: broken endpoint formatting in v1.x (#3831)
  content/influxdb/cloud/reference/api/influxdb-1x/_index.md
Labels: fix

#3840 Feat/3414 debug pprof
  content/influxdb/v2.1/reference/internals/runtime.md
Labels: api, OSS

#3845 fix: caption shortcode
  assets/styles/layouts/article/_captions.scss
Labels: fix

#3851 fix: link Resolving High Cardinality to Quotas. (#3850)
  content/influxdb/cloud/account-management/limits.md
  content/influxdb/v2.1/write-data/best-practices/resolve-high-cardinality.md
Labels: InfluxDB Cloud, fix

#3858 fix: global write request limit is still 50 MB for the time being.
  content/influxdb/cloud/account-management/limits.md
Labels: fix

#3883 fix: update token placeholder v2.1
  content/influxdb/cloud/influxdb-templates/create.md
  content/influxdb/cloud/organizations/buckets/create-bucket.md
  content/influxdb/cloud/organizations/buckets/delete-bucket.md
  content/influxdb/v2.1/influxdb-templates/create.md
  content/influxdb/v2.1/query-data/execute-queries/influx-api.md
  content/influxdb/v2.1/security/tokens/use-tokens.md
Labels: fix

#3898 Add security section to influxdb/v2.2/reference/release-notes/influxdb.md
  content/influxdb/v2.2/reference/release-notes/influxdb.md
Labels: OSS, v2.2

#3910 Flux 0.160 and 0.161
  content/flux/v0.x/release-notes.md
Labels: Flux
