Repository influxdata/docs-v2, pull requests merged in 2022-08, with the labels that each got.

#4295 feat: documented invokable scripts within tasks functionality in the CLI
  content/influxdb/v2.4/reference/cli/influx/task/create.md
  content/influxdb/v2.4/reference/cli/influx/task/update.md
Labels: feat

#4302 Update and fix use templates
  content/influxdb/cloud/influxdb-templates/use.md
  content/influxdb/v2.3/influxdb-templates/use.md
Labels: api, CLI

#4236 Feat/cloud task scripts
  content/influxdb/cloud/process-data/manage-tasks/_index.md
  content/influxdb/v2.3/process-data/get-started.md
  content/influxdb/v2.3/process-data/manage-tasks/_index.md
  content/influxdb/v2.3/process-data/manage-tasks/create-task.md
Labels: enhancement, api

#4329 chore: update property names in redocly config.
  api-docs/.redocly.yaml
Labels: chore

#4346 fix(tasks): options (#4345).
  content/influxdb/v2.3/process-data/task-options.md
Labels: fix

#4350 fix: use proper command for brew install postman
  content/influxdb/v2.3/api-guide/postman.md
Labels: fix

#4382 feat: add update header and add note to edge data replication
  content/influxdb/v2.2/write-data/replication/_index.md
  content/influxdb/v2.2/write-data/replication/replicate-data.md
  content/influxdb/v2.3/write-data/replication/_index.md
  content/influxdb/v2.3/write-data/replication/replicate-data.md
  content/influxdb/v2.4/write-data/replication/_index.md
  content/influxdb/v2.4/write-data/replication/replicate-data.md
Labels: feat

#4391 hotfix(api): add info content for v2.4 API
  api-docs/README.md
  api-docs/openapi/content/v2.4/info.yml
  api-docs/openapi/content/v2.4/v1compat/info.yml
Labels: api
