Repository influxdata/docs-v2, pull requests merged in 2023-04, with the labels that each got.

#4853 fix(cloud-iox): infinite cardinality (#4851)
  content/influxdb/cloud-iox/_index.md
  content/influxdb/cloud-iox/write-data/best-practices/schema-design.md
Labels: fix

#4865 Cloud Dedicated primers v1 API: auth and write
  content/influxdb/cloud-dedicated/primers/_index.md
  content/influxdb/cloud-dedicated/primers/api/_index.md
  content/influxdb/cloud-dedicated/primers/api/v1/_index.md
  content/influxdb/cloud-dedicated/primers/api/v2/_index.md
  content/influxdb/cloud-dedicated/write-data/_index.md
  content/influxdb/cloud-dedicated/write-data/best-practices/_index.md
  content/influxdb/cloud-dedicated/write-data/best-practices/schema-design.md
  content/influxdb/cloud-dedicated/write-data/csv/_index.md
  content/influxdb/cloud-dedicated/write-data/csv/telegraf.md
  content/influxdb/cloud-dedicated/write-data/migrate-data/_index.md
  content/influxdb/cloud-dedicated/write-data/migrate-data/migrate-1x-to-iox.md
  content/influxdb/cloud-dedicated/write-data/migrate-data/migrate-tsm-to-iox.md
  content/influxdb/cloud-dedicated/write-data/use-telegraf/_index.md
  content/influxdb/cloud-dedicated/write-data/use-telegraf/configure/_index.md
  content/influxdb/cloud-dedicated/write-data/use-telegraf/configure/auto-config.md
  content/influxdb/cloud-dedicated/write-data/use-telegraf/configure/manual-config.md
  content/influxdb/cloud-dedicated/write-data/use-telegraf/dual-write.md
  content/influxdb/cloud-dedicated/write-data/use-telegraf/telegraf-configs/_index.md
  content/influxdb/cloud-dedicated/write-data/use-telegraf/telegraf-configs/create.md
  content/influxdb/cloud-dedicated/write-data/use-telegraf/telegraf-configs/remove.md
  content/influxdb/cloud-dedicated/write-data/use-telegraf/telegraf-configs/update.md
  content/influxdb/cloud-dedicated/write-data/use-telegraf/telegraf-configs/view.md
  content/influxdb/cloud-dedicated/write-data/v1-write-api.md
  layouts/shortcodes/api/cloud/v2-prefer.html
  shared/text/api/cloud-dedicated/basic-auth.js
  shared/text/api/cloud-dedicated/basic-auth.sh
  shared/text/api/cloud-dedicated/querystring-auth.js
  shared/text/api/cloud-dedicated/querystring-auth.sh
  shared/text/api/cloud-dedicated/token-auth.js
  shared/text/api/cloud-dedicated/token-auth.sh
Labels: InfluxDB Cloud Dedicated

#4873 Dedicated v1 write
  content/influxdb/cloud-dedicated/primers/api/v1/_index.md
  layouts/shortcodes/api/cloud/v2-prefer.html
Labels: InfluxDB Cloud Dedicated

#4880 fix(cloud-dedicated): cleanup
  content/influxdb/cloud-dedicated/get-started/write.md
  content/influxdb/cloud-dedicated/primers/api/v1/_index.md
  content/influxdb/cloud-dedicated/primers/api/v2/_index.md
  shared/text/api/cloud-dedicated/basic-auth.js
  shared/text/api/cloud-dedicated/basic-auth.sh
  shared/text/api/cloud-dedicated/querystring-auth.js
  shared/text/api/cloud-dedicated/querystring-auth.sh
  shared/text/api/cloud-dedicated/token-auth-v2-write.sh
  shared/text/api/cloud-dedicated/token-auth.js
  shared/text/api/cloud-dedicated/token-auth.sh
Labels: fix

#4883 chore: remove references to unsigned
  content/influxdb/cloud-iox/query-data/tools/grafana.md
Labels: chore

#4888 fix(cloud-iox): schema design corrections (closes #4851):
  content/influxdb/cloud-iox/query-data/sql/basic-query.md
  content/influxdb/cloud-iox/query-data/sql/explore-schema.md
  content/influxdb/cloud-iox/write-data/best-practices/schema-design.md
  content/influxdb/v2.7/reference/glossary.md
Labels: fix

#4890 fix(cloud-dedicated): get-started write
  content/influxdb/cloud-dedicated/get-started/query.md
  content/influxdb/cloud-dedicated/get-started/write.md
  content/influxdb/cloud-dedicated/primers/api/v1/_index.md
  content/influxdb/cloud-dedicated/primers/api/v2/_index.md
  shared/text/api/cloud-dedicated/bearer-auth-v1-query.sh
  shared/text/api/cloud-dedicated/bearer-auth-v1-write.sh
  shared/text/api/cloud-dedicated/bearer-auth-v2-write.sh
  shared/text/api/cloud-dedicated/token-auth-v1-query.sh
  shared/text/api/cloud-dedicated/token-auth-v1-write.sh
Labels: fix

#4897 fix(cloud-dedicated): v1 API examples and params for /query
  content/influxdb/cloud-dedicated/primers/api/v1/_index.md
Labels: fix

#4898 fix(cloud-dedicated): minor word change
  content/influxdb/cloud-dedicated/primers/api/v1/_index.md
Labels: fix

#4906 feat(iox): add a reference list for client libraries
  content/influxdb/cloud-dedicated/reference/client-libraries/_index.md
  content/influxdb/cloud-dedicated/reference/client-libraries/flight-sql/_index.md
  content/influxdb/cloud-dedicated/reference/client-libraries/flight-sql/go-flightsql.md
  content/influxdb/cloud-dedicated/reference/client-libraries/flight-sql/python-flightsql-dbapi.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v1/_index.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/_index.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/arduino.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/csharp.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/dart.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/go.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/java.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/javascript/_index.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/javascript/browser.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/javascript/nodejs/_index.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/javascript/nodejs/install.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/javascript/nodejs/query.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/javascript/nodejs/write.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/kotlin.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/php.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/python.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/r.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/ruby.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/scala.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/swift.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v3/_index.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v3/python.md
  content/influxdb/cloud-serverless/query-data/execute-queries/flight-sql/python.md
  content/influxdb/cloud-serverless/query-data/tools/pandas.md
  content/influxdb/cloud-serverless/query-data/tools/pyarrow.md
  content/influxdb/cloud-serverless/reference/client-libraries/_index.md
  content/influxdb/cloud-serverless/reference/client-libraries/flight-sql/_index.md
  content/influxdb/cloud-serverless/reference/client-libraries/flight-sql/go-flightsql.md
  content/influxdb/cloud-serverless/reference/client-libraries/flight-sql/python-flightsql-dbapi.md
  content/influxdb/cloud-serverless/reference/client-libraries/v1/_index.md
  content/influxdb/cloud-serverless/reference/client-libraries/v2/_index.md
  content/influxdb/cloud-serverless/reference/client-libraries/v2/arduino.md
  content/influxdb/cloud-serverless/reference/client-libraries/v2/csharp.md
  content/influxdb/cloud-serverless/reference/client-libraries/v2/dart.md
  content/influxdb/cloud-serverless/reference/client-libraries/v2/go.md
  content/influxdb/cloud-serverless/reference/client-libraries/v2/java.md
  content/influxdb/cloud-serverless/reference/client-libraries/v2/javascript/_index.md
  content/influxdb/cloud-serverless/reference/client-libraries/v2/javascript/browser.md
  content/influxdb/cloud-serverless/reference/client-libraries/v2/javascript/nodejs/_index.md
  content/influxdb/cloud-serverless/reference/client-libraries/v2/javascript/nodejs/install.md
  content/influxdb/cloud-serverless/reference/client-libraries/v2/javascript/nodejs/write.md
  content/influxdb/cloud-serverless/reference/client-libraries/v2/kotlin.md
  content/influxdb/cloud-serverless/reference/client-libraries/v2/php.md
  content/influxdb/cloud-serverless/reference/client-libraries/v2/python.md
  content/influxdb/cloud-serverless/reference/client-libraries/v2/r.md
  content/influxdb/cloud-serverless/reference/client-libraries/v2/ruby.md
  content/influxdb/cloud-serverless/reference/client-libraries/v2/scala.md
  content/influxdb/cloud-serverless/reference/client-libraries/v2/swift.md
  content/influxdb/cloud-serverless/reference/client-libraries/v3/_index.md
  content/influxdb/cloud-serverless/reference/client-libraries/v3/python.md
Labels: feat

#4912 fix(v3): misc. fixes for Telegraf, examples, bucket schemas
  content/influxdb/cloud-dedicated/write-data/csv/telegraf.md
  content/influxdb/cloud-serverless/admin/buckets/manage-explicit-bucket-schemas.md
  content/influxdb/cloud-serverless/write-data/csv/telegraf.md
  content/influxdb/cloud-serverless/write-data/use-telegraf/_index.md
  content/influxdb/cloud-serverless/write-data/use-telegraf/configure/manual-config.md
  content/influxdb/cloud-serverless/write-data/use-telegraf/dual-write.md
  content/telegraf/v1.26/configuration.md
Labels: fix

#4914 fix(dedicated): microsecond precision, token types, error examples
  content/influxdb/cloud-dedicated/primers/api/v1/_index.md
  content/influxdb/cloud-dedicated/primers/api/v2/_index.md
Labels: fix

#4913 fix: small typo in remote update docs example
  content/influxdb/v2.2/reference/cli/influx/remote/update.md
  content/influxdb/v2.3/reference/cli/influx/remote/update.md
  content/influxdb/v2.4/reference/cli/influx/remote/update.md
  content/influxdb/v2.5/reference/cli/influx/remote/update.md
  content/influxdb/v2.6/reference/cli/influx/remote/update.md
  content/influxdb/v2.7/reference/cli/influx/remote/update.md
Labels: fix
