Repository influxdata/docs-v2, pull requests merged in 2023-06, with the labels that each got.

#4975 fix(v2): create a token with CLI and API, revert old warning, add exa…
  content/influxdb/v2.7/security/tokens/create-token.md
Labels: fix

#4995 feat: improve delete predicate keyword escaping requirements
  content/influxdb/v2.7/reference/syntax/delete-predicate.md
Labels: feat

#4996 chore(docs): Update storage-limits to remove directions to contact support
  content/influxdb/cloud-serverless/reference/internals/storage-limits.md
Labels: chore

#5004 fix(dedicated): influxctl create token (closes #5000):
  content/influxdb/cloud-dedicated/admin/tokens/create.md
  content/influxdb/cloud-dedicated/reference/cli/influxctl/token/create.md
  content/influxdb/cloud-serverless/admin/tokens/create-token.md
  content/influxdb/cloud/security/tokens/create-token.md
Labels: fix
