Repository influxdata/docs-v2, pull requests merged in 2023-08, with the labels that each got.

#5066 chore(ci): Vale: ignore words, ignore spelling and ellipses in table
  .ci/vale/styles/InfluxDataDocs/Ellipses.yml
  .ci/vale/styles/InfluxDataDocs/Spelling.yml
  .ci/vale/styles/InfluxDataDocs/Terms/query-functions.txt
  .ci/vale/styles/InfluxDataDocs/WordList.yml
  .ci/vale/styles/Vocab/InfluxData/accept.txt
  .vale.ini
Labels: chore

#5065 chore(v3): configure client library cert paths for windows
  content/influxdb/cloud-dedicated/get-started/query.md
  content/influxdb/cloud-dedicated/query-data/sql/execute-queries/python.md
  content/influxdb/cloud-dedicated/reference/client-libraries/flight/go-flight.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v1/_index.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/_index.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v3/python.md
  content/influxdb/cloud-serverless/get-started/query.md
  content/influxdb/cloud-serverless/query-data/sql/execute-queries/python.md
  content/influxdb/cloud-serverless/reference/client-libraries/flight/go-flight.md
  content/influxdb/cloud-serverless/reference/client-libraries/v1/_index.md
  content/influxdb/v1.5/tools/api_client_libraries.md
  content/influxdb/v1.6/tools/api_client_libraries.md
  content/influxdb/v1.7/tools/api_client_libraries.md
  content/influxdb/v1.8/tools/api_client_libraries.md
Labels: chore

#5068 chore(telegraf): add Avro input format (parser).
  content/telegraf/v1.27/data_formats/input/_index.md
  content/telegraf/v1.27/data_formats/input/avro.md
  content/telegraf/v1.27/release-notes-changelog.md
Labels: chore

#5072 chore(telegraf): Update input and output data formats from Telegraf docs (Closes #5054):
  .ci/vale/styles/Vocab/InfluxData/accept.txt
  content/telegraf/v1.27/commands.md
  content/telegraf/v1.27/configuration.md
  content/telegraf/v1.27/configure_plugins/template-patterns.md
  content/telegraf/v1.27/data_formats/_index.md
  content/telegraf/v1.27/data_formats/input/_index.md
  content/telegraf/v1.27/data_formats/input/avro.md
  content/telegraf/v1.27/data_formats/input/binary.md
  content/telegraf/v1.27/data_formats/input/collectd.md
  content/telegraf/v1.27/data_formats/input/csv.md
  content/telegraf/v1.27/data_formats/input/dropwizard.md
  content/telegraf/v1.27/data_formats/input/form_urlencoded.md
  content/telegraf/v1.27/data_formats/input/graphite.md
  content/telegraf/v1.27/data_formats/input/grok.md
  content/telegraf/v1.27/data_formats/input/influx.md
  content/telegraf/v1.27/data_formats/input/json.md
  content/telegraf/v1.27/data_formats/input/json_v2.md
  content/telegraf/v1.27/data_formats/input/logfmt.md
  content/telegraf/v1.27/data_formats/input/nagios.md
  content/telegraf/v1.27/data_formats/input/opentsdb.md
  content/telegraf/v1.27/data_formats/input/prometheus-remote-write.md
  content/telegraf/v1.27/data_formats/input/value.md
  content/telegraf/v1.27/data_formats/input/wavefront.md
  content/telegraf/v1.27/data_formats/input/xml.md
  content/telegraf/v1.27/data_formats/input/xpath_json.md
  content/telegraf/v1.27/data_formats/input/xpath_msgpack.md
  content/telegraf/v1.27/data_formats/input/xpath_protobuf.md
  content/telegraf/v1.27/data_formats/output/_index.md
  content/telegraf/v1.27/data_formats/output/carbon2.md
  content/telegraf/v1.27/data_formats/output/graphite.md
  content/telegraf/v1.27/data_formats/output/influx.md
  content/telegraf/v1.27/data_formats/output/json.md
  content/telegraf/v1.27/data_formats/output/messagepack.md
  content/telegraf/v1.27/data_formats/output/nowmetric.md
  content/telegraf/v1.27/data_formats/output/splunkmetric.md
  content/telegraf/v1.27/glossary.md
  content/telegraf/v1.27/metrics.md
Labels: chore

#5081 chore(ci): Add vale script, configuration, and fixes
  .ci/vale/styles/InfluxDataDocs/Branding.yml
  .ci/vale/styles/InfluxDataDocs/Spelling.yml
  .ci/vale/styles/InfluxDataDocs/Terms/configuration-terms.txt
  .ci/vale/styles/Vocab/Cloud-Dedicated/accept.txt
  .ci/vale/styles/Vocab/Cloud-Serverless/accept.txt
  .ci/vale/styles/Vocab/InfluxData/accept.txt
  .ci/vale/vale.sh
  .vscode/settings.json
  content/influxdb/cloud-dedicated/.vale.ini
  content/influxdb/cloud-dedicated/.vscode/settings.json
  content/influxdb/cloud-dedicated/process-data/visualize/grafana.md
  content/influxdb/cloud-dedicated/process-data/visualize/superset.md
  content/influxdb/cloud-dedicated/reference/cli/influxctl/_index.md
  content/influxdb/cloud-dedicated/reference/client-libraries/flight/python-flightsql-dbapi.md
  content/influxdb/cloud-dedicated/reference/client-libraries/v2/javascript/browser.md
  content/influxdb/cloud-dedicated/reference/influxql/_index.md
  content/influxdb/cloud-dedicated/reference/influxql/math-operators.md
  content/influxdb/cloud-dedicated/write-data/use-telegraf/configure/_index.md
  content/influxdb/cloud-serverless/.vale.ini
  content/influxdb/cloud-serverless/.vscode/settings.json
  content/influxdb/cloud-serverless/process-data/visualize/grafana.md
  content/influxdb/cloud-serverless/process-data/visualize/superset.md
  content/influxdb/cloud-serverless/reference/cli/influx/remote/create.md
  content/influxdb/cloud-serverless/reference/cli/influx/replication/create.md
  content/influxdb/cloud-serverless/reference/client-libraries/flight/python-flightsql-dbapi.md
  content/influxdb/cloud-serverless/reference/client-libraries/v2/javascript/browser.md
  content/influxdb/cloud-serverless/reference/influxql/_index.md
  content/influxdb/cloud-serverless/reference/influxql/math-operators.md
  content/influxdb/cloud-serverless/write-data/migrate-data/migrate-tsm-to-iox.md
  content/influxdb/cloud-serverless/write-data/use-telegraf/configure/_index.md
Labels: chore

#5093 fix: Clarify valuecounter aggregator
  data/telegraf_plugins.yml
Labels: fix

#5103 chore: explain null tags in primary keys
  content/influxdb/cloud-serverless/get-started/_index.md
  content/influxdb/cloud-serverless/reference/glossary.md
  content/influxdb/cloud-serverless/write-data/best-practices/schema-design.md
Labels: chore

#5099 feat: influxctl v2.0.2
  data/products.yml
Labels: feat

#5107 chore: indicate that tag values cannot be empty in line protocol
  content/influxdb/v2.7/reference/syntax/line-protocol.md
Labels: chore

#5117 chore(serverless-grafana): update "create a datasource" for InfluxQL
  content/influxdb/cloud-serverless/process-data/visualize/grafana.md
  static/img/influxdb/cloud-serverless-grafana-influxdb-datasource.png
Labels: chore
