Repository influxdata/docs-v2, pull requests merged in 2023-12, with the labels that each got.

#5259 fix(telegraf): describe gpg key compatibility (closes #5231)
  content/telegraf/v1/install.md
  test.Dockerfile
Labels: fix

#5275 chore: add note about partial write failures
  api-docs/cloud-serverless/ref.yml
Labels: chore

#5273 feature(v3): Cloud Dedicated write API: partial writes write good lines and reject bad li…
  api-docs/cloud-dedicated/ref.yml
  api-docs/cloud-serverless/ref.yml
  content/influxdb/cloud-dedicated/guides/api-compatibility/v1/_index.md
  content/influxdb/cloud-dedicated/guides/api-compatibility/v2/_index.md
  content/influxdb/cloud-dedicated/write-data/troubleshoot.md
  content/influxdb/cloud-serverless/guides/api-compatibility/v1/_index.md
  content/influxdb/cloud-serverless/guides/api-compatibility/v2/_index.md
  content/influxdb/cloud-serverless/write-data/troubleshoot.md
Labels: api

#5286 fix(v2): Bad formatting in documentation (Chapt on series)
  content/influxdb/v2/reference/key-concepts/data-elements.md
  layouts/shortcodes/product-name.html
Labels: fix

#5288 Fix(v3): Update Go Arrow package version
  content/influxdb/cloud-dedicated/get-started/query.md
  content/influxdb/cloud-dedicated/query-data/execute-queries/client-libraries/go.md
  content/influxdb/cloud-dedicated/reference/client-libraries/flight/go-flight.md
  content/influxdb/cloud-serverless/get-started/query.md
  content/influxdb/cloud-serverless/query-data/execute-queries/client-libraries/go.md
  content/influxdb/cloud-serverless/reference/client-libraries/flight/go-flight.md
  content/influxdb/clustered/get-started/query.md
  content/influxdb/clustered/query-data/execute-queries/client-libraries/go.md
  content/influxdb/clustered/reference/client-libraries/flight/go-flight.md
Labels: fix
