Repository influxdata/docs-v2, pull requests merged in 2023-10, with the labels that each got.

#5164 Fix: Placeholder cleanup
  .ci/vale/styles/Vocab/InfluxData/accept.txt
  content/influxdb/cloud-dedicated/get-started/write.md
  content/influxdb/cloud-dedicated/guides/api-compatibility/v1/_index.md
  content/influxdb/cloud-dedicated/guides/api-compatibility/v2/_index.md
  content/influxdb/cloud-dedicated/reference/client-libraries/flight/python-flight.md
  content/influxdb/cloud-dedicated/reference/sample-data.md
  content/influxdb/cloud-serverless/guides/api-compatibility/v2/_index.md
  content/influxdb/clustered/get-started/write.md
  content/influxdb/clustered/guides/api-compatibility/v1/_index.md
  content/influxdb/clustered/guides/api-compatibility/v2/_index.md
  content/influxdb/clustered/reference/client-libraries/flight/python-flight.md
  content/influxdb/clustered/reference/sample-data.md
Labels: fix

#5174 Fix: Broken link in troubleshoot.md
  content/influxdb/cloud-dedicated/query-data/execute-queries/troubleshoot.md
Labels: fix

#5179 fix: Use AZURE_CLIENT_ID
  content/influxdb/clustered/install/auth.md
Labels: fix

#4137 feat: add hh_node measurement
  content/platform/monitoring/influxdata-platform/tools/measurements-internal.md
Labels: Enterprise 1.x, feat

#5190 feat(clustered): add s3 permissions policy
  content/influxdb/clustered/install/prerequisites.md
Labels: feat

#5192 chore(api): add API compatibility overview to API ref
  api-docs/cloud-dedicated/content/info.yml
  api-docs/cloud-dedicated/content/tag-groups.yml
  api-docs/cloud-dedicated/ref.yml
  api-docs/cloud-serverless/content/info.yml
  api-docs/cloud-serverless/content/tag-groups.yml
  api-docs/cloud-serverless/ref.yml
  api-docs/cloud/ref.yml
  api-docs/clustered/content/info.yml
  api-docs/clustered/ref.yml
  api-docs/generate-api-docs.sh
  api-docs/getswagger.sh
  api-docs/template.hbs
  api-docs/v2/ref.yml
Labels: chore

#5197 fix(clustered): remove link to inaccessible google doc
  content/influxdb/clustered/admin/users/_index.md
Labels: fix

#5202 chore(v3): There is no index of Tag Values, Tag Values are "just data…
  content/influxdb/cloud-dedicated/write-data/best-practices/schema-design.md
  content/influxdb/cloud-serverless/write-data/best-practices/schema-design.md
  content/influxdb/clustered/write-data/best-practices/schema-design.md
Labels: chore
