Repository influxdata/docs-v2, pull requests merged in 2023-01, with the labels that each got.

#4686 feat: add examples of escaping predicates for delete
  content/influxdb/v2.6/reference/syntax/delete-predicate.md
Labels: feat

#4685 chore: defaults were not accurate for several config options
  content/influxdb/v2.6/reference/config-options.md
Labels: chore

#4693 fix: recommend powershell as cmd doesn't have full compatibility
  content/influxdb/v2.6/tools/influx-cli.md
Labels: fix

#4709 feat: add new config value log-timedout-queries
  content/enterprise_influxdb/v1.11/administration/configure/config-data-nodes.md
Labels: feat

#4724 chore(grafana): Rework the documentation for a release instead of from source.
  content/influxdb/cloud-iox/visualize-data/grafana.md
Labels: chore

#4733 fix(telegraf): update v1.20, v1.21, v1.22 install instructions
  content/telegraf/v1.20/introduction/installation.md
  content/telegraf/v1.21/introduction/installation.md
  content/telegraf/v1.22/install.md
Labels: fix
