Repository influxdata/docs-v2, pull requests merged in 2024-08, with the labels that each got.

#5548 fix(clustered): clustered reference docs for `influxctl` incorrectly …
  content/influxdb/clustered/reference/cli/influxctl/cluster/list.md
Labels: fix

#5545 fix(v2): http-write-timeout
  .ci/vale/styles/InfluxDBv2/ServerConfig.yml
  .ci/vale/styles/InfluxDBv2/Terms/query-functions.txt
  .ci/vale/styles/InfluxDBv2/Terms/server-config-options.txt
  .ci/vale/styles/config/vocabularies/InfluxDataDocs/accept.txt
  Dockerfile.pytest
  content/influxdb/v2/.vale.ini
  content/influxdb/v2/reference/config-options.md
  lefthook.yml
  test/scripts/prepare-content.sh
Labels: fix

#5543 feat(v3): Port Java client library examples to Dedicated and Clustered.
  content/influxdb/cloud-dedicated/reference/client-libraries/v3/java.md
  content/influxdb/cloud-serverless/reference/client-libraries/v3/java.md
  content/influxdb/clustered/reference/client-libraries/v3/java.md
Labels: feat

#5552 fix(v2): missing volumes section in Docker compose example
  content/influxdb/v2/install/use-docker-compose.md
Labels: fix

#5547 fix(v3): Broken URL due to missing delete-predicate.md (closes #5448)
  content/influxdb/cloud-serverless/reference/cli/influx/delete/_index.md
  content/influxdb/cloud-serverless/reference/syntax/delete-predicate.md
Labels: fix

#5553 fix: link to missing Clustered users page
  content/influxdb/clustered/install/configure-cluster/directly.md
Labels: fix

#5554 fix(v2): missing v2 beta upgrade
  .ci/Dockerfile.remark
  .ci/remark-lint/package.json
  .ci/remark-lint/yarn.lock
  content/influxdb/v2/install/_index.md
  content/influxdb/v2/install/upgrade/v2-beta-to-v2.md
Labels: fix

#5557 fix(write-api): Serverless write 201 response codes
  api-docs/cloud-serverless/v2/ref.yml
  content/influxdb/cloud-serverless/write-data/troubleshoot.md
Labels: fix

#5564 fix(write-api): Write requests outside retention period will return 422
  api-docs/cloud-dedicated/v2/ref.yml
  api-docs/cloud-serverless/v2/ref.yml
  content/influxdb/cloud-dedicated/write-data/troubleshoot.md
  content/influxdb/cloud-serverless/write-data/troubleshoot.md
Labels: fix

#5566 Enterprise 1.11.6 release notes
  content/enterprise_influxdb/v1/about-the-project/release-notes.md
  data/products.yml
Labels: Enterprise 1.x

#5569 InfluxDB 2.7.9 and 2.7.10
  content/influxdb/v2/reference/release-notes/influxdb.md
  data/products.yml
Labels: InfluxDB v2, OSS
